package com.bumb.speedmath;

/**
 * Created by manisharora on 8/11/13.
 */
public enum ProblemTypeEnum {
    ONE_DIGIT_ADDITION(1),
    ONE_DIGIT_SUBTRACTION(1),
    ONE_DIGIT_MULTIPLICATION(1),
    ONE_DIGIT_DIVISION_WITHOUT_DECIMAL_RESULT(1),
    ONE_DIGIT_DIVISION_WITH_DECIMAL_RESULT(1),
    TWO_DIGIT_ADDITION(2),
    ONE_DIGIT_ONE_DECIMAL_DIGIT_ADDITION(2),
    TWO_DIGIT_SUBTRACTION(2),
    ONE_DIGIT_ONE_DECIMAL_DIGIT_SUBTRACTION(2),
    TWO_DIGIT_ONE_DIGIT_MULTIPLICATION(2),
    TWO_DIGIT_ONE_DIGIT_DIVISION(2),
    THREE_DIGIT_TWO_DIGIT_ADDITION(3),
    THREE_DIGIT_ADDITION(3),
    THREE_DIGIT_TWO_DIGIT_SUBTRACTION(3),
    THREE_DIGIT_SUBTRACTION(3),
    TWO_DIGIT_ONE_DECIMAL_DIGIT_ADDITION(3),
    TWO_DIGIT_ONE_DECIMAL_DIGIT_SUBTRACTION(3),
    TWO_DIGIT_MULTIPLICATION(3);

    int score;
    ProblemTypeEnum(int score) {
        this.score = score;
    }

    public int getScore() {
        return this.score;
    }
}